version: '3'

services:
  sosemivigelant-scg:
    container_name: tuktuk-test
    ports:
      - "8082:8081"
    environment:
      - NODE_ENV=production
    image: registry.dekker.gdn/tuktuk-scg-scrapper:latest
    volumes:
      - server-data:/home/app/packages/server/data

volumes:
  server-data:
