version: '3'

services:
  sosemivigelant-scg:
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    image: registry.dekker.gdn/tuktuk-scg-scrapper:stable
    volumes:
      - server-data:/home/app/packages/server/data

volumes:
  server-data:
