version: '3.2'

services:
  scg-provider:
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=production
    build:
      args:
        TEAMCITY_BUILD_NUMBER: ${BUILD_NUMBER}

  proxy:
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    build:
      args:
        TEAMCITY_BUILD_NUMBER: ${BUILD_NUMBER}
