version: '3.2'

services:
  scg-provider:
    container_name: tuktuk-scg-provider-prod
    environment:
      - NODE_ENV=production
    image: cr.yandex/crpsmb4r20h7k2j950c4/tuktuk-scg-scrapper-scg-provider:stable
    volumes:
      - server-data:/home/app/packages/server/data

  proxy:
    container_name: tuktuk-proxy-prod
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    image: cr.yandex/crpsmb4r20h7k2j950c4/tuktuk-scg-scrapper-proxy:stable

  storage:
    container_name: tuktuk-storage-prod
    environment:
      - NODE_ENV=production
    image: cr.yandex/crpsmb4r20h7k2j950c4/tuktuk-scg-scrapper-storage:stable

  frontend:
    container_name: tuktuk-frontend-prod
    environment:
      - NODE_ENV=production
    image: cr.yandex/crpsmb4r20h7k2j950c4/tuktuk-scg-scrapper-frontend:stable

volumes:
  server-data:
