const MtgGoldfishMap = {
    M21: 'Core Set 2021',
    IKO: 'Ikoria Lair of Behemoths',
    THB: 'Theros Beyond Death',
    ELD: 'Throne of Eldraine',
    M20: 'Core Set 2020',
    WAR: 'War of the Spark',
    RNA: 'Ravnica Allegiance',
    GRN: 'Guilds of Ravnica',
    M19: 'Core Set 2019',
    DOM: 'Dominaria',
    RIX: 'Rivals of Ixalan',
    XLN: 'Ixalan',
    HOU: 'Hour of Devastation',
    AKH: 'Amonkhet',
    MS3: 'Amonkhet Invocations',
    AER: 'Aether Revolt',
    KLD: 'Kaladesh',
    MS2: 'Kaladesh Inventions',
    ORI: 'Magic Origins',
    M15: 'Magic 2015',
    M14: 'Magic 2014',
    EMN: 'Eldritch Moon',
    SOI: 'Shadows over Innistrad',
    OGW: 'Oath of the Gatewatch',
    BFZ: 'Battle for Zendikar',
    EXP: 'Zendikar Expeditions',
    DTK: 'Dragons of Tarkir',
    FRF: 'Fate Reforged',
    KTK: 'Khans of Tarkir',
    JOU: 'Journey into Nyx',
    BNG: 'Born of the Gods',
    THS: 'Theros',
    DGM: "Dragon's Maze",
    GTC: 'Gatecrash',
    RTR: 'Return to Ravnica',
    MH1: 'Modern Horizons',
    MM3: 'Modern Masters 2017',
    MM2: 'Modern Masters 2015',
    MD1: 'Modern Event Deck',
    MMA: 'Modern Masters',
    M13: 'Magic 2013',
    M12: 'Magic 2012',
    M11: 'Magic 2011',
    M10: 'Magic 2010',
    '10E': 'Tenth Edition',
    '9ED': 'Ninth Edition',
    '8ED': 'Eighth Edition',
    AVR: 'Avacyn Restored',
    DKA: 'Dark Ascension',
    ISD: 'Innistrad',
    NPH: 'New Phyrexia',
    MBS: 'Mirrodin Besieged',
    SOM: 'Scars of Mirrodin',
    ROE: 'Rise of the Eldrazi',
    WWK: 'Worldwake',
    ZEN: 'Zendikar',
    ARB: 'Alara Reborn',
    CON: 'Conflux',
    ALA: 'Shards of Alara',
    EVE: 'Eventide',
    SHM: 'Shadowmoor',
    MOR: 'Morningtide',
    LRW: 'Lorwyn',
    FUT: 'Future Sight',
    PLC: 'Planar Chaos',
    TSP: 'Time Spiral',
    TSB: 'Timeshifted',
    CSP: 'Coldsnap',
    DIS: 'Dissension',
    GPT: 'Guildpact',
    RAV: 'Ravnica',
    SOK: 'Saviors of Kamigawa',
    BOK: 'Betrayers of Kamigawa',
    CHK: 'Champions of Kamigawa',
    '5DN': 'Fifth Dawn',
    DST: 'Darksteel',
    MRD: 'Mirrodin',
    '7ED': 'Seventh Edition',
    '6ED': 'Classic Sixth Edition',
    '5ED': 'Fifth Edition',
    '4ED': 'Fourth Edition',
    '3ED': 'Revised Edition',
    '2ED': 'Unlimited Edition',
    LEB: 'Limited Edition Beta',
    LEA: 'Limited Edition Alpha',
    SCG: 'Scourge',
    LGN: 'Legions',
    ONS: 'Onslaught',
    JUD: 'Judgment',
    TOR: 'Torment',
    OD: 'Odyssey',
    AP: 'Apocalypse',
    PS: 'Planeshift',
    IN: 'Invasion',
    PR: 'Prophecy',
    NE: 'Nemesis',
    MM: 'Mercadian Masques',
    UD: "Urza's Destiny",
    UL: "Urza's Legacy",
    UZ: "Urza's Saga",
    EX: 'Exodus',
    ST: 'Stronghold',
    TE: 'Tempest',
    WL: 'Weatherlight',
    VI: 'Visions',
    MI: 'Mirage',
    ALL: 'Alliances',
    HML: 'Homelands',
    ICE: 'Ice Age',
    FEM: 'Fallen Empires',
    DRK: 'The Dark',
    LEG: 'Legends',
    ATQ: 'Antiquities',
    ARN: 'Arabian Nights',
    SLD: 'Secret Lair',
    PSLD: 'Secret Lair Promos',
    'MED-WAR': 'War of the Spark Masterpieces',
    'MED-RNA': 'Ravnica Allegiance Masterpieces',
    'MED-GRN': 'Guilds of Ravnica Masterpieces',
    GK1: 'Guilds of Ravnica Guild Kits',
    GK2: 'Ravnica Allegiance Guild Kits',
    SS1: 'Signature Spellbook Jace',
    SS2: 'Signature Spellbook Gideon',
    SS3: 'Signature Spellbook Chandra',
    MB1: 'Mystery Booster',
    '2XM': 'Double Masters',
    UMA: 'Ultimate Masters',
    'PRM-UMA': 'Ultimate Box Topper',
    A25: 'Masters 25',
    IMA: 'Iconic Masters',
    EMA: 'Eternal Masters',
    PZ2: 'Treasure Chest',
    PZ1: 'Legendary Cube',
    TPR: 'Tempest Remastered',
    VMA: 'Vintage Masters',
    PRM: 'Promotional',
    'PRM-BAB': 'Buy-A-Box Promos',
    'PRM-SSP': 'Standard Showdown Promos',
    'PRM-UGF': "Ugin's Fate Promos",
    PTG: 'Ponies The Galloping',
    'PRM-SDCC18': 'SDCC 2018 Promos',
    'PRM-SDCC17': 'SDCC 2017 Promos',
    'PRM-SDCC16': 'SDCC 2016 Promos',
    'PRM-SDCC15': 'SDCC 2015 Promos',
    'PRM-SDCC14': 'SDCC 2014 Promos',
    'PRM-SDCC13': 'SDCC 2013 Promos',
    'PRM-CHP': 'Champs Promos',
    'PRM-FNM': 'FNM Promos',
    'PRM-GDP': 'Game Day Promos',
    'PRM-GWP': 'Gateway Promos',
    'PRM-GPP': 'Grand Prix Promos',
    'PRM-GUR': 'Guru Lands',
    'PRM-JSS': 'JSS/MSS Promos',
    'PRM-JUD': 'Judge Promos',
    'PRM-LPC': 'Launch Party Cards',
    'PRM-MPR': 'Magic Player Rewards',
    'PRM-MED': 'Media Promos',
    'PRM-PRE': 'Prerelease Cards',
    'PRM-PTP': 'Pro Tour Promos',
    'PRM-REL': 'Release Event Cards',
    'PRM-SPO': 'Special Occasion',
    'PRM-MSC': 'Unique and Miscellaneous Promos',
    'PRM-WPN': 'WPN & Gateway Promos',
    POR: 'Portal',
    PO2: 'Portal Second Age',
    PTK: 'Portal Three Kingdoms',
    S00: 'Starter 2000',
    S99: 'Starter 1999',
    JMP: 'Jumpstart',
    C20: 'Commander 2020',
    C19: 'Commander 2019',
    C18: 'Commander 2018',
    CM2: 'Commander Anthology Volume II',
    BBD: 'Battlebond',
    E02: 'Explorers of Ixalan',
    C17: 'Commander 2017',
    CMA: 'Commander Anthology',
    C16: 'Commander 2016',
    C15: 'Commander 2015',
    C14: 'Commander 2014',
    C13: 'Commander 2013',
    CMD: 'Commander',
    CN2: 'Conspiracy Take the Crown',
    CNS: 'Conspiracy',
    DDU: 'Duel Decks Elves vs Inventors',
    DDT: 'Duel Decks Merfolk vs Goblins',
    DDS: 'Duel Decks Mind vs Might',
    DDR: 'Duel Decks Nissa vs Ob Nixilis',
    DDQ: 'Duel Decks Blessed vs Cursed',
    DDP: 'Duel Decks Zendikar vs Eldrazi',
    DDO: 'Duel Decks Elspeth vs Kiora',
    DDN: 'Duel Decks Speed vs Cunning',
    DDM: 'Duel Decks Jace vs Vraska',
    DDL: 'Duel Decks Heroes vs Monsters',
    DDK: 'Duel Decks Sorin vs Tibalt',
    DDJ: 'Duel Decks Izzet vs Golgari',
    DDI: 'Duel Decks Venser vs Koth',
    DDH: 'Duel Decks Ajani vs Nicol Bolas',
    DDG: 'Duel Decks Knights vs Dragons',
    DDF: 'Duel Decks Elspeth vs Tezzeret',
    DDE: 'Duel Decks Phyrexia vs the Coalition',
    DDD: 'Duel Decks Garruk vs Liliana',
    DDC: 'Duel Decks Divine vs Demonic',
    DD2: 'Duel Decks Jace vs Chandra',
    EVG: 'Duel Decks Elves vs Goblins',
    ME4: 'Masters Edition IV',
    ME3: 'Masters Edition III',
    ME2: 'Masters Edition II',
    MED: 'Masters Edition',
    V17: 'From the Vault Transform',
    V16: 'From the Vault Lore',
    V15: 'From the Vault Angels',
    V14: 'From the Vault Annihilation',
    V13: 'From the Vault Twenty',
    V12: 'From the Vault Realms',
    V11: 'From the Vault Legends',
    V10: 'From the Vault Relics',
    V09: 'From the Vault Exiled',
    DRB: 'From the Vault Dragons',
    PC1: 'Planechase',
    PC2: 'Planechase 2012',
    PCA: 'Planechase Anthology',
    PD3: 'Premium Deck Series Graveborn',
    PD2: 'Premium Deck Series Fire and Lightning',
    H09: 'Premium Deck Series Slivers',
    E01: 'Archenemy Nicol Bolas',
    ARC: 'Archenemy',
    BTD: 'Beatdown Box Set',
    BRB: 'Battle Royale Box Set',
    ATH: 'Anthologies',
    CHR: 'Chronicles',
    UND: 'Unsanctioned',
    UST: 'Unstable',
    UNH: 'Unhinged',
    UGL: 'Unglued',
};

export const getMtgGoldfishSet = (set: string) => {
    return MtgGoldfishMap[set] || set;
};
