name: Docker

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker-compose build --parallel

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Push stable
      run: node ./tools/tag.js

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITAL_OCEAN_HOST }}
        key: ${{ secrets.DIGITAL_OCEAN_KEY }}
        username: ${{ secrets.DIGITAL_OCEAN_USER }}
        script: |
          cd ~/tuktuk-scg-scrapper
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml pull --no-parallel
          docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --no-build -d
