name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker-compose build

    - name: Tag stable
      run: docker tag registry.dekker.gdn/tuktuk-scg-scrapper:latest registry.dekker.gdn/tuktuk-scg-scrapper:stable

    - name: Push latest
      run: docker push registry.dekker.gdn/tuktuk-scg-scrapper:latest

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 14.1

    - name: Push stable
      run: node ./tools/tag.js

