name: Run unit-tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.1

      - name: Install dependencies
      - uses: borales/actions-yarn@v1.17.3
        with:
          cmd: install --frozen-lockfile

      - name: Run tests
      - uses: borales/actions-yarn@v1.17.3
        with:
          cmd: test:ci
