name: Unit-tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.1

      - name: Install dependencies
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: install --frozen-lockfile --network-concurrency 1

      - name: Run tests
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: test:ci
